---
title: "Perception of Nudges Analysis"
author: "Mariam Abdelnabi"
date: '2022-10-19'
output: pdf_document
---

```{r}
library(tidyverse)
library(emmeans)
library(afex)
library(ggplot2)
library(cowplot)
library(readxl)
library(foreign)
library(MASS)
library(Hmisc)
library(reshape2)
logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- odds / (1 + odds)
  return(prob)
}
```

### Cleaning Data

```{r}
perc_nudges <- Perception_of_Nudges_Covid_Dataset
df_all <- read_excel("arab_countries.xlsx")
df_kenya <- read_excel("kenya.xlsx")

df_arabkn <- read_excel("arab_countries.xlsx")

df_qatar <- read_excel("qatar.xlsx")
```

```{r}
perc_nudges <- perc_nudges %>% 
  dplyr::select(c(RespondentID,nationality,Locals,sex,age,education,occupation,speciality,income,marital_status,children,height,weight,chronic_illness,`Self Health`,`Covid-19 Concern`,PCR_times,positive_PCR,family_PCR,`Positive Family Dummy`,`GPS Tracking`,`Q2 dummy`,`Floor Markers`,`Public Shaming`,`Park Squares`,`Publish Causes of Infection`,`Elderly Letters`,`F&V Proximity`,`Plastic Cutlery`,`Charitable Donations`,`Food Waste`,`Cigarette Butts`,`Knowledge Sharing`,`Physical Education`,`Utility Bills`,`Covid-19 Concern`,Country,BMI,Condition))
```

```{r}
#factorizing the within-level variables into the
#two factor levels each has
perc_nudges <- perc_nudges %>% 
  mutate(nationality=factor(nationality,levels=c("Afghanistan","Algeria","Australia","Austria",
                                                 "Bahrain","Bangladesh","Brazil","Canada","Comoros",
                                                 "Cyprus","Egypt","Eritrea","France",
                                                 "Germany","Holy See","India",
                                                 "Indonesia","Iran (Islamic Republic of",
                                                 "Iraq","Ireland","Jordan","Kuwait",
                                                 "Lebanon","Liberia","Libya",
                                                 "Monaco","Morocco","New Zealand",
                                                 "Nigeria","Oman","Pakistan","Palestine",
                                                 "Philippines","Poland","Portugal",
                                                 "Russian Federation","Saudi Arabia","Somalia",
                                                 "South Africa","Sri Lanka","Sudan","Syrian Arab Republic","Tunisia","Turkey","Ukraine","United Arab Emirates","United Kingdom of Great Britain","United Republic of Tanzania","United States of America","Uzbekistan","Yemen","Zimbabwe")))
```

```{r}
#rename arabic answers to english
perc_nudges[perc_nudges == "أنثى"] <- "Female"
perc_nudges[perc_nudges == "ذكر"] <- "Male"

perc_nudges[perc_nudges == "تعليم الثانوي"] <- "Secondary education"
perc_nudges[perc_nudges == "درجة البكالوريوس"] <- "Undergraduate degree"
perc_nudges[perc_nudges == "درجة الدكتوراه"] <- "Doctoral degree"
perc_nudges[perc_nudges == "درجة الماجستير"] <- "Graduate degree"
perc_nudges[perc_nudges == "مؤهلات مهنية"] <- "Professional qualification"
perc_nudges[perc_nudges == "لا مؤهلات رسمية"] <- "No professional qualification"

perc_nudges[perc_nudges=="Student"] <- "student"
perc_nudges[perc_nudges=="Married"] <- "married"
perc_nudges[perc_nudges=="Divorced"] <- "divorced"
perc_nudges[perc_nudges=="Single"] <- "single"
perc_nudges[perc_nudges=="Widowed"] <- "widowed"
```

```{r}
#continuing factorisation
perc_nudges <- perc_nudges %>% 
  mutate(sex=factor(sex,levels=c("Female","Male")),
         education=factor(education,levels=c("Secondary education","Undergraduate degree","Graduate degree","Doctoral degree","Professional qualification","No professional qualification")),
         occupation=factor(occupation,levels=c("Academic Staff","Admin","Administrative Staff","faculty","student")),
         income=factor(income,levels=c("low","middle","high")),
         marital_status=factor(marital_status,levels=c("divorced","married","single","widowed")),
         positive_PCR=factor(positive_PCR,levels=c("No","Yes")),
         family_PCR=factor(family_PCR,levels=c("No","Yes")))
```

```{r}
children <- read_excel("children.xlsx")
perc_nudges <- cbind(perc_nudges,children)
#dropping non-numeric children variable
perc_nudges <- perc_nudges[,-11]
```

```{r}
df_all <- df_all %>% 
  mutate(country=factor(country,levels=c("AE","EG","LB","SA","KN")))

perc_nudges <- perc_nudges %>% 
  mutate(Condition=factor(Condition,levels=c(0,1),labels=c("control","treatment")))

df_all <- df_all %>% 
  mutate(group=factor(group,levels=c("control","treatment")))

df_arabkn <- df_arabkn %>% 
  mutate(country=factor(country,levels=c("arab","KN")))


df_arabkn[df_arabkn=="SA"] <- "arab"
df_arabkn[df_arabkn=="LB"] <- "arab"
df_arabkn[df_arabkn=="EG"] <- "arab"
df_arabkn[df_arabkn=="AE"] <- "arab"
df_all <- subset(df_all, !country == "KN")
```

```{r}
### COVID
  ### Non intrusive
names(perc_nudges)[names(perc_nudges) == "family_PCR"] <- "pcrfam"
names(perc_nudges)[names(perc_nudges) == "positive_PCR"] <- "pcrself"
names(perc_nudges)[names(perc_nudges) == "Q2 dummy"] <- "billboards"
names(perc_nudges)[names(perc_nudges) == "Floor Markers"] <- "markers"
names(perc_nudges)[names(perc_nudges) == "Park Squares"] <- "squares"
names(perc_nudges)[names(perc_nudges) == "Publish Causes of Infection"] <- "infection"
names(perc_nudges)[names(perc_nudges) == "Elderly Letters"] <- "letters"
names(perc_nudges)[names(perc_nudges) == "F&V Proximity"] <- "proximity"

### COVID
  ### Intrusive
names(perc_nudges)[names(perc_nudges) == "Public Shaming"] <- "shaming"
names(perc_nudges)[names(perc_nudges) == "GPS Tracking"] <- "gps"


### ENVIRONMENT
names(perc_nudges)[names(perc_nudges) == "Plastic Cutlery"] <- "plastic"
names(perc_nudges)[names(perc_nudges) == "Food Waste"] <- "food"
names(perc_nudges)[names(perc_nudges) == "Cigarette Butts"] <- "cigarette"

### MONEY
names(perc_nudges)[names(perc_nudges) == "Charitable Donations"] <- "charity"
names(perc_nudges)[names(perc_nudges) == "Utility Bills"] <- "bills"

### KNOWLEDGE
names(perc_nudges)[names(perc_nudges) == "Knowledge Sharing"] <- "knowledge"
names(perc_nudges)[names(perc_nudges) == "Physical Education"] <- "PE"


names(df_all)[names(df_all) == "infections"] <- "infection"
```

```{r}
perc_nudges <- perc_nudges %>% 
  mutate(billboards=factor(billboards,levels=c(0,1),labels=c("disapprove","approve")),
         markers=factor(markers,levels=c(0,1),labels=c("disapprove","approve")),
         squares=factor(squares,levels=c(0,1),labels=c("disapprove","approve")),
         infection=factor(infection,levels=c(0,1),labels=c("disapprove","approve")),
         letters=factor(letters,levels=c(0,1),labels=c("disapprove","approve")),
         proximity=factor(proximity,levels=c(0,1),labels=c("disapprove","approve")),
         shaming=factor(shaming,levels=c(0,1),labels=c("disapprove","approve")),
         gps=factor(gps,levels=c(0,1),labels=c("disapprove","approve")),
         plastic=factor(plastic,levels=c(0,1),labels=c("disapprove","approve")),
         food=factor(food,levels=c(0,1),labels=c("disapprove","approve")),
         cigarette=factor(cigarette,levels=c(0,1),labels=c("disapprove","approve")),
         charity=factor(charity,levels=c(0,1),labels=c("disapprove","approve")),
         bills=factor(bills,levels=c(0,1),labels=c("disapprove","approve")),
         knowledge=factor(knowledge,levels=c(0,1),labels=c("disapprove","approve")),
         PE=factor(PE,levels=c(0,1),labels=c("disapprove","approve")))

df_all <- df_all %>% 
  mutate(billboards=factor(billboards,levels=c("disapprove","approve")),
         markers=factor(markers,levels=c("disapprove","approve")),
         squares=factor(squares,levels=c("disapprove","approve")),
         infections=factor(infections,levels=c("disapprove","approve")),
         letters=factor(letters,levels=c("disapprove","approve")),
         proximity=factor(proximity,levels=c("disapprove","approve")),
         shaming=factor(shaming,levels=c("disapprove","approve")),
         gps=factor(gps,levels=c("disapprove","approve")),
         plastic=factor(plastic,levels=c("disapprove","approve")),
         food=factor(food,levels=c("disapprove","approve")),
         cigarette=factor(cigarette,levels=c("disapprove","approve")),
         charity=factor(charity,levels=c("disapprove","approve")),
         bills=factor(bills,levels=c("disapprove","approve")),
         knowledge=factor(knowledge,levels=c("disapprove","approve")),
         PE=factor(PE,levels=c("disapprove","approve")))

df_qatar <- df_qatar %>% 
  mutate(tissue=factor(tissue,levels=c("disapprove","approve")),
         grievances=factor(grievances,levels=c("disapprove","approve")),
         plastic=factor(plastic,levels=c("disapprove","approve")),
         elecpay=factor(elecpay,levels=c("disapprove","approve")),
         charity=factor(charity,levels=c("disapprove","approve")),
         food=factor(food,levels=c("disapprove","approve")),
         bills=factor(bills,levels=c("disapprove","approve")),
         litter=factor(litter,levels=c("disapprove","approve")),
         minorities=factor(minorities,levels=c("disapprove","approve")),
         training=factor(training,levels=c("disapprove","approve")),
         cigarette=factor(cigarette,levels=c("disapprove","approve")),
         footwear=factor(footwear,levels=c("disapprove","approve")),
         support=factor(support,levels=c("disapprove","approve")),
         knowledge=factor(knowledge,levels=c("disapprove","approve")),
         PE=factor(PE,levels=c("disapprove","approve")))
```


```{r}
df_all %>%
        group_by(plastic) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(food) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(charity) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(bills) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(PE) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(cigarette) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(knowledge) %>% 
        summarise(nsize=n())
```


```{r}
perc_nudges <- perc_nudges[,-c(2,3,8,11:16,36)]
```

================================================================================
================================================================================

### Counts

```{r}
df_all %>%
        group_by(gps) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(billboards) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(markers) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(shaming) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(squares) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(infections) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(letters) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(proximity) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(plastic,group,country) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(charity) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(food,group,country) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(cigarette,group,country) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(knowledge) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(PE) %>% 
        summarise(nsize=n())

df_all %>%
        group_by(bills) %>% 
        summarise(nsize=n())
```

```{r}
perc_nudges %>%
        group_by(Country,gps) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,billboards) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,markers) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,shaming) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,squares) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,infection) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,letters) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,proximity) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,plastic) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,charity) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,food) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,cigarette) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,knowledge) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,PE) %>% 
        summarise(nsize=n())

perc_nudges %>%
        group_by(Country,bills) %>% 
        summarise(nsize=n())
```

```{r}
perc_nudges %>%
        group_by(Country,shaming) %>% 
        summarise(nsize=n())
```

================================================================================
================================================================================

### TREATMENT-BASED COMPARISONS COVID NUDGES

```{r}
df_debiasing <- subset(perc_nudges,perc_nudges$Country!="LB")
df_forecasting <- subset(perc_nudges,perc_nudges$Country=="LB")
```

================================================================================
================================================================================

#### DEBIASING COVID NUDGES

```{r}
chisq.test(df_debiasing$Condition,df_debiasing$proximity)

chisq.test(df_debiasing$Condition,df_debiasing$gps)
chisq.test(df_debiasing$Condition,df_debiasing$billboards)
chisq.test(df_debiasing$Condition,df_debiasing$markers)
chisq.test(df_debiasing$Condition,df_debiasing$shaming)
chisq.test(df_debiasing$Condition,df_debiasing$squares)
chisq.test(df_debiasing$Condition,df_debiasing$infection)
chisq.test(df_debiasing$Condition,df_debiasing$letters)
```

```{r}
summary(glm(proximity ~ Condition,data = df_debiasing,family = "binomial"))
logit2prob(coef(s1))

summary(glm(gps ~ Condition,data = df_debiasing,family = "binomial"))
s1 <- summary(glm(billboards ~ Condition,data = df_debiasing,family = "binomial"))
summary(glm(markers ~ Condition,data = df_debiasing,family = "binomial"))
summary(glm(shaming ~ Condition,data = df_debiasing,family = "binomial"))
summary(glm(squares ~ Condition,data = df_debiasing,family = "binomial"))
summary(glm(infection ~ Condition,data = df_debiasing,family = "binomial"))
summary(glm(letters ~ Condition,data = df_debiasing,family = "binomial"))
```

```{r}
summary(glm(proximity ~ Country,data = df_debiasing,family = "binomial"))
s1 <- summary(glm(gps ~ Country,data = df_debiasing,family = "binomial"))
logit2prob(coef(s1))

summary(glm(billboards ~ Country,data = df_debiasing,family = "binomial"))
summary(glm(markers ~ Country,data = df_debiasing,family = "binomial"))
summary(glm(shaming ~ Country,data = df_debiasing,family = "binomial"))
summary(glm(squares ~ Country,data = df_debiasing,family = "binomial"))
summary(glm(infection ~ Country,data = df_debiasing,family = "binomial"))
s1 <- summary(glm(letters ~ Country,data = df_debiasing,family = "binomial"))
```



#### SUPER FORECASTING COVID NUDGES

```{r}
chisq.test(df_forecasting$Condition,df_forecasting$gps)
chisq.test(df_forecasting$Condition,df_forecasting$squares)

chisq.test(df_forecasting$Condition,df_forecasting$billboards)
chisq.test(df_forecasting$Condition,df_forecasting$markers)
chisq.test(df_forecasting$Condition,df_forecasting$shaming)
chisq.test(df_forecasting$Condition,df_forecasting$infection)
chisq.test(df_forecasting$Condition,df_forecasting$letters)
chisq.test(df_forecasting$Condition,df_forecasting$proximity)
```

```{r}
summary(glm(gps ~ country,data = forecasting,family = "binomial"))
summary(glm(squares ~ country,data = forecasting,family = "binomial"))
summary(glm(billboards ~ country,data = forecasting,family = "binomial"))
summary(glm(markers ~ country,data = forecasting,family = "binomial"))
summary(glm(shaming ~ country,data = forecasting,family = "binomial"))
summary(glm(infection ~ country,data = forecasting,family = "binomial"))
summary(glm(letters ~ country,data = forecasting,family = "binomial"))
summary(glm(proximity ~ country,data = forecasting,family = "binomial"))
```

================================================================================
================================================================================

